version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '8080:8080'
    environment:
      - MONGODB_URI=mongodb+srv://hasani:Hasani1234@cluster.vewgwip.mongodb.net/Restuarant-service

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'